### PR TITLE
Some more changes

### PR DESCRIPTION
**Pull request by jesserockz**
A few changes, please see commit list

@martgras Please let me know if anything I am doing doesn't make sense for the component.
I am testing this with my SDM230 modbus meter.

### CODE REVIEW

**Review by martgras — COMMENTED** [review]
I had the calculation in my code initially but it seems a few device don't follow the standard / convention that a register contains 16 bits. 

https://www.edpdistribuicao.pt/sites/edd/files/normative_docs/DEF-C44-509.pdf.
The seems to use one address to return a variable amount of data .

@nikito7 uses this definition for such a device. (https://github.com/nikito7/edpbox/blob/dev/esphome/EB3-21.8.14.yaml)

You would expect that register_count: 2 is used for the U_DWORD sensors but the default of 1 seems to work here.
I haven't seen any other device behaving like this - or did I misunderstand it it @nikito7 

````yaml
      - id: ActPowL1
        name: "${dev} Active Power L1"
        address: 0x0073
        offset: 0
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 0
        device_class: power
        unit_of_measurement: "W"

      - id: ActPowL1Exp
        name: "${dev} Active Power L1 Export"
        address: 0x0073
        offset: 4
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 0
        device_class: power
        unit_of_measurement: "W"
        internal: true # disable sensor
````

Can we calculate the default value in python based on CONF_VALUE_TYPE? (1 for WORD, 2 FOR DWORD ...)

**Comment by nikito7** [comment]
My device is non standard

request count 1 got 4 bytes for 32bits

**Comment by jesserockz** [comment]
> Can we calculate the default value in python based on CONF_VALUE_TYPE? (1 for WORD, 2 FOR DWORD ...)

Yes we can do this in a custom validation.

**Comment by martgras** [comment]
What if we use register_count: 0  for auto counting and use any other value as an override for some odd devices 
Same for offset - what about using 2 different units "1b" for one byte and "1w" or "1r" for 2 bytes ? (although I don't know how to do this in the python part)

**Comment by jesserockz** [comment]
You can also just not set a default for register_count, and set in a validator based on the type. This would respect the user entered value.

I think offset should always be the number of registers not bytes, otherwise its going to get very confusing.

While I am not saying to ignore completely, also writing a **modbus** controller that has to add a whole bunch of stuff for some devices that do not follow modbus protocol specifications is getting extremely complex and hard to understand.

Having the byte count for a single register not being 2 bytes also messes up reading the correct data from the byte buffer modbus_sensor.

Once again, not against supporting the non-standard, but it just needs to be well thought out and be secondary to the protocol.

**Comment by nikito7** [comment]
Variable register size could be done with text sensors. It worked with response size.

You can ignore non-standard "32bits count 1".
But you will need to add it later any way

For me modbus is just hex values

This is a bad dejavu from home assistant modbus.

My 32bits is a single register (request count 1)

Standard 32bits are two 16bits registers (request count 2)

**Comment by nikito7** [comment]
Buffer_offset/position allow change type.
Other solutions maybe not

```yaml
      - id: ActPowExp
        name: "${dev} Active Power Export"
        address: 0x0073
        offset: 28
        modbus_functioncode: "read_input_registers"
        value_type: U_DWORD
        accuracy_decimals: 0
        device_class: power
        unit_of_measurement: "W"
        internal: true # disable sensor

# type changes ####

      - id: PowFac
        name: "${dev} Power Factor"
        address: 0x0073
        offset: 32
        unit_of_measurement: "pu"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 3
        filters:
          - multiply: 0.001
        device_class: power_factor
```

This is just to reduce modbus requests

Most of features of first version of @martgras component will be needed. Soon or later

**Comment by jesserockz** [comment]
I guess the hard part when using different register byte counts is calculating how many registers to request, and then what the actual buffer offset is. Perhaps the parent component needs to configure byte count for every register for a specific modbus address (As each device should at least adhere to the same count when calling read_input_registers)


Here is some of my config for my SDM meter:

```yaml
  - platform: modbus_controller
    modbus_functioncode: read_input_registers
    address: 0x00
    offset: 0x00
    id: controller_voltage
    name: SDM Voltage
    unit_of_measurement: V
    device_class: voltage
    accuracy_decimals: 2
    state_class: measurement
    value_type: FP32


  - platform: modbus_controller
    modbus_functioncode: read_input_registers
    address: 0x00
    offset: 0x06
    id: controller_current
    name: SDM Current
    unit_of_measurement: A
    device_class: current
    accuracy_decimals: 3
    state_class: measurement
    value_type: FP32
```

**Comment by nikito7** [comment]
@jesserockz your PR is working for me...

offset changed from bytes to .... i dont know 😅

```yaml

  - platform: modbus_controller
    name: "${dev} T1 Vazio"
    address: 0x0026
    offset: 0
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    last_reset_type: auto

  - platform: modbus_controller
    name: "${dev} T2 Ponta"
    address: 0x0026
    offset: 2
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    last_reset_type: auto

  - platform: modbus_controller
    name: "${dev} T3 Cheias"
    address: 0x0026
    offset: 4
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    state_class: measurement
    device_class: energy
    last_reset_type: auto
```

**Comment by jesserockz** [comment]
Its the register offset (assuming 2 bytes per register)

offset 2 and 4 for SDM are phase 2 and phase 3 which I dont have and that is why mine skips to 6

**Comment by nikito7** [comment]
It request 6... It's needed "register_count" or alike as before

```
[23:29:21][V][component:206]: Component modbus_controller took a long time for an operation (0.06 s).
[23:29:21][V][component:207]: Components should block for at most 20-30ms.
[23:29:29][V][modbus_controller:138]: Updating modbus component
[23:29:30][V][modbus_controller:120]: Range : 26 Size: 6 (4) skip: 0
[23:29:30][V][modbus_controller:032]: Sending next modbus command to device 1 register 0x26
[23:29:30][V][modbus:223]: Modbus write: 01.04.00.26.00.06.91.C3 (8)
[23:29:30][V][modbus_controller:380]: Command sent 4 0x26 6
[23:29:30][V][modbus:058]: Modbus received Byte  1 (0X1)
[23:29:30][V][modbus:058]: Modbus received Byte  4 (0X4)
[23:29:30][V][modbus:058]: Modbus received Byte  24 (0X18)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  2 (0X2)
[23:29:30][V][modbus:058]: Modbus received Byte  158 (0X9e)
[23:29:30][V][modbus:058]: Modbus received Byte  203 (0Xcb)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  1 (0X1)
[23:29:30][V][modbus:058]: Modbus received Byte  154 (0X9a)
[23:29:30][V][modbus:058]: Modbus received Byte  32 (0X20)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  4 (0X4)
[23:29:30][V][modbus:058]: Modbus received Byte  144 (0X90)
[23:29:30][V][modbus:058]: Modbus received Byte  23 (0X17)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  0 (0X0)
[23:29:30][V][modbus:058]: Modbus received Byte  13 (0Xd)
[23:29:30][V][modbus:058]: Modbus received Byte  233 (0Xe9)
[23:29:30][V][modbus_controller:049]: Modbus response queued
[23:29:30][V][component:206]: Component modbus took a long time for an operation (0.15 s).
[23:29:30][V][component:207]: Components should block for at most 20-30ms.
[23:29:30][V][modbus_controller:057]: Process modbus response for address 0x26 size: 24
[23:29:30][V][modbus_controller:078]: data for register address : 0x26 :
```

**Comment by jesserockz** [comment]
Yeah, so in that case what I mentioned above might work, and saves from setting it on every sensor as they really all need to match

> Perhaps the parent component needs to configure byte count for every register for a specific modbus address (As each device should at least adhere to the same count when calling read_input_registers)

So it would be like this:

```yaml
modbus_controller:
  - address: 0x00
    ...
    register_bytes: 4 # defaults to 2
```

**Comment by nikito7** [comment]
No... only 32bits registers are no standard 

```value_type: U_DWORD```

I have 16bits standard  too

**Comment by jesserockz** [comment]
I am confused now...haha

You mean the same device has different length registers?

**Comment by jesserockz** [comment]
So `Modbus write: 01.04.00.26.00.06.91.C3 (8)` should be returning `12` bytes of data, but it is returning `24` above, but the data is packed into the first `12` bytes only.

**Comment by nikito7** [comment]
01.04.00.26.00.06.91.C3

The correct is 

01.04.00.26.00.03.xx.xx

**Comment by nikito7** [comment]
> So `Modbus write: 01.04.00.26.00.06.91.C3 (8)` should be returning `12` bytes of data, but it is returning `24` above, but the data is packed into the first `12` bytes only.

Yessss

**Comment by jesserockz** [comment]
Ah yes I see now. 

So what I am asking is that does the same device return less than 32 bits per register?
If not then the above yaml/config option would fix that

**Comment by jesserockz** [comment]
We only need that single config number that can then be used in various calculations in the code universally for that modbus device address. So it would be less config for a user and be different per device if you had standard and non-standard on the same bus

**Comment by nikito7** [comment]
U_WORD is standard 16bits

**Comment by jesserockz** [comment]
> U_WORD is standard 16bits

Yeah, but does the device actually have a `U_WORD` register that will only return 16 bits? If so then calculations get a lot harder for register requesting and buffer offset in returned data...

**Comment by nikito7** [comment]
But I have more

0001 is 12 bytes
0004 is 6 bytes

```
text_sensor:

  - platform: modbus_controller
    name: "${dev} 0x0001 Clock" 
    modbus_functioncode: "read_input_registers" 
    address: 0x0001
    offset: 0
    raw_encode: COMMA
    response_size: 12
    icon: mdi:chip

  - platform: modbus_controller 
    name: "${dev} Info: Firmware Core" 
    modbus_functioncode: "read_input_registers" 
    address: 0x0004
    offset: 0
    raw_encode: NONE
    response_size: 6
    icon: mdi:chip
```

**Comment by nikito7** [comment]
Old config

Offset in bytes

```
# begin 0x006C range
# dont remove middle registers of a range
# disable it only with, internal: true

      - id: VolL1
        name: "${dev} Voltage L1"
        address: 0x006C
        offset: 0
        unit_of_measurement: "V"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.1
        device_class: voltage

      - id: CurL1
        name: "${dev} Current L1"
        address: 0x006C
        offset: 2
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.1
        device_class: current

      - id: VolL2
        name: "${dev} Voltage L2"
        address: 0x006C
        offset: 4
        unit_of_measurement: "V"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.1
        device_class: voltage

      - id: CurL2
        name: "${dev} Current L2"
        address: 0x006C
        offset: 6
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.1
        device_class: current

      - id: VolL3
        name: "${dev} Voltage L3"
        address: 0x006C
        offset: 8
        unit_of_measurement: "V"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.1
        device_class: voltage

      - id: CurL3
        name: "${dev} Current L3"
        address: 0x006C
        offset: 10
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        accuracy_decimals: 1
        filters:
          - multiply: 0.1
        device_class: current

      - id: Cur
        name: "${dev} Current"
        address: 0x006C
        offset: 12
        unit_of_measurement: "A"
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
        filters:
          - multiply: 0.1
        accuracy_decimals: 1
        device_class: current






# eof 0x006C range
```

**Comment by jesserockz** [comment]
What device is it? Is there a document for the registers?

**Comment by nikito7** [comment]
https://github.com/nikito7/edpbox/raw/dev/DEF-C44-509.pdf

**Comment by jesserockz** [comment]
Oh man, that makes a lot more sense as to why all the options were there before...
But still doesn't make it easy...haha

**Comment by nikito7** [comment]
@martgras have done a good job 😁

**Comment by nikito7** [comment]
For sensor is needed "32bits count 1 vs 32bits count 2"

For text_sensor code could be different, it's not so important as sensor

I avoid request multiple registers in text_sensor. Will be to hard do that

All single register/request above 2 bytes it's non-standard

**Comment by jesserockz** [comment]
Ok, I will take another look at some of the logic I changed and revert some changes.

Perhaps `offset` should be `buffer_offset` as a config option then to make it more clear its not a register offset

**Review by martgras — APPROVED** [review]

**Review by martgras — APPROVED** [review]

**Review by martgras — APPROVED** [review]

**Review by martgras — APPROVED** [review]

**Review by martgras — APPROVED** [review]

**Comment by jesserockz** [comment]
So many approvals...haha

**Comment by martgras** [comment]
I would prefer offset to use a unit like bytes or words but  we can also use buffer_offset instead. No strong option either way.

And since I finished the day in a beer garden today I'm not going to look at code today anymore 🙂

**Comment by jesserockz** [comment]
~~byte_offset would be fine too. =)~~

Ah a unit, yeah that could help =)

**Comment by martgras** [comment]
A note to ModbusController::create_register_ranges()
Your new implementation breaks on my controller because the number of addresses is not counted correctly. You are relying on offset to calculate the number of registers which doesn't work for these device with return more than a word as a result. 
The code calculates the number of registers wrong for my device on some ranges.(epever : http://www.solar-elektro.cz/data/dokumenty/1733_modbus_protocol.pdf)
Haven't found the exact reason - probably because offset is used. 
My intention is that (byte-)offset specifies the position in the result buffer - decoupled from the associated modbus register address. 
The number of registers required for the 0x4 (READ_INPUT_REGISTERS) parameter defined only by the number of registers in a range.

However why fiddle with offsets in bytes or words at all. 
ModbusController::create_register_ranges now automatically combines requests to sequential addresses.

With [my latest commit](https://github.com/martgras/esphome/commit/0b34cb69508bad9d564917842b2c3d433924c8ac) you can define the registers just using thier address. 
register_count is caluclated for all standard devices. Others can override the value.


This definition creates a single request to address 0x3000 for 6 registers
`force_new_range: true` can be used to prevent a sensor from merged in previous range
````yaml
sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_voltage
    name: "array_rated_voltage"
    address: 0x3000
    unit_of_measurement: "V"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_current
    name: "array_rated_current"
    address: 0x3001
    unit_of_measurement: "A"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD


  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_power
    name: "array_rated_power"
    address: 0x3002
    register_count: 2
    unit_of_measurement: "W"
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD_R

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_voltage
    name: "battery_rated_voltage"
    address: 0x3004
    unit_of_measurement: "V"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_current
    name: "battery_rated_current"
    address: 0x3005
    unit_of_measurement: "A"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
````

Also I tried to address the other points you raised in the code review with the previous commits

**Comment by jesserockz** [comment]
Yeah awesome. I have not had a chance to come back to testing your PR since making the last change here but I will give it another try during the week hopefully.

**Pull request closed without merging**
